# Preprocessing - Scale Transforms
Copyright (c) Microsoft Corporation. All rights reserved.<br>
Licensed under the MIT License.

In [1]:
import azureml.dataprep as dprep

DataPrep provides a number of transformation functions to scale numeric columns.

## Min-Max Scaler

The min-max scaler scales all values in a column to a desired range (typically [0, 1]). Also commonly known as feature scaling, or unity-based normalization.

First, we will load a dataset containing information about baseball players. We will only keep a few columns.

In [2]:
df = dprep.read_csv(path='https://dpreptestfiles.blob.core.windows.net/testfiles/baseball-players.csv')
df = df.keep_columns(columns=['playerID', 'weight', 'height'])
df = df.to_number(columns=['weight', 'height'])
df.head(25)

,playerID,weight,height
0,aardsda01,205,75
1,aaronha01,180,72
2,aaronto01,190,75
3,aasedo01,190,75
4,abadan01,184,73
5,abadfe01,220,73
6,abadijo01,192,72
7,abbated01,170,71
8,abbeybe01,175,71
9,abbeych01,169,68
10,abbotda01,190,71
11,abbotfr01,180,70
12,abbotgl01,200,78
13,abbotje01,190,74
14,abbotji01,200,75
15,abbotku01,180,71
16,abbotky01,200,76
17,abbotod01,180,74
18,abbotpa01,185,75
19,aberal01,195,74
20,abercda01,"azureml.dataprep.native.DataPrepError(""'Micros...","azureml.dataprep.native.DataPrepError(""'Micros..."
21,abercre01,215,75
22,abernbi01,190,70
23,abernbr01,185,73
24,abernte01,210,74

Using `get_profile()`, we can see the shape of the numeric columns, such as the min, max, count, and number of error values.

In [3]:
df.get_profile()

ColumnProfile
    name: playerID
    type: FieldType.STRING

    min: aardsda01
    max: zwilldu01
    count: 18589.0
    missing_count: 0.0
    not_missing_count: 18589.0
    percent_missing: 0.0
    error_count: 0.0
    empty_count: 0.0


ColumnProfile
    name: weight
    type: FieldType.DECIMAL

    min: 65.0
    max: 320.0
    count: 18589.0
    missing_count: 0.0
    not_missing_count: 18589.0
    percent_missing: 0.0
    error_count: 872.0
    empty_count: 0.0


    Quantiles:
         0.1%: 129.29877671957675
           1%: 159.99953151689223
           5%: 159.99654576856648
          25%: 169.99780768694487
          50%: 183.55268060052987
          75%: 196.6551175790482
          95%: 222.46017100866118
          99%: 245.24211967545628
        99.9%: 279.7918333333329

    std: 20.998279187359834
    mean: 185.56267991194906

ColumnProfile
    name: height
    type: FieldType.DECIMAL

    min: 43.0
    max: 83.0
    count: 18589.0
    missing_count: 0.0
    not_missing_count: 18589.0
    percent_missing: 0.0
    error_count: 809.0
    empty_count: 0.0


    Quantiles:
         0.1%: 62.945827067669164
           1%: 68.99758782005755
           5%: 68.99719101123586
          25%: 70.38494889805855
          50%: 72.0
          75%: 73.99753399388054
          95%: 76.0
          99%: 78.3517553191489
        99.9%: 80.62964464925763

    std: 2.598992233721804
    mean: 72.2352643419572

To apply min-max scaling, we can simply call the function `min_max_scaler` on the dataflow and specify the column name. This will trigger a full data scan over the column to determine the min and max values and perform the scaling. Note that the min and max values of the column is preserved at this point. If the same dataflow steps are performed over a different data set, the min-max scaler must be re-executed.

In [4]:
df2 = df.min_max_scale(column='weight')
df2.head(25)

,playerID,weight,height
0,aardsda01,0.54902,75
1,aaronha01,0.45098,72
2,aaronto01,0.490196,75
3,aasedo01,0.490196,75
4,abadan01,0.466667,73
5,abadfe01,0.607843,73
6,abadijo01,0.498039,72
7,abbated01,0.411765,71
8,abbeybe01,0.431373,71
9,abbeych01,0.407843,68
10,abbotda01,0.490196,71
11,abbotfr01,0.45098,70
12,abbotgl01,0.529412,78
13,abbotje01,0.490196,74
14,abbotji01,0.529412,75
15,abbotku01,0.45098,71
16,abbotky01,0.529412,76
17,abbotod01,0.45098,74
18,abbotpa01,0.470588,75
19,aberal01,0.509804,74
20,abercda01,"azureml.dataprep.native.DataPrepError(""'Micros...","azureml.dataprep.native.DataPrepError(""'Micros..."
21,abercre01,0.588235,75
22,abernbi01,0.490196,70
23,abernbr01,0.470588,73
24,abernte01,0.568627,74

By looking at the data profile, we can see that the weight column is now scaled - the min is 0 and the max is 1. Any error values and missing values from the source column are preserved.

In [5]:
df2.get_profile()

ColumnProfile
    name: playerID
    type: FieldType.STRING

    min: aardsda01
    max: zwilldu01
    count: 18589.0
    missing_count: 0.0
    not_missing_count: 18589.0
    percent_missing: 0.0
    error_count: 0.0
    empty_count: 0.0


ColumnProfile
    name: weight
    type: FieldType.DECIMAL

    min: 0.0
    max: 1.0
    count: 18589.0
    missing_count: 0.0
    not_missing_count: 18589.0
    percent_missing: 0.0
    error_count: 872.0
    empty_count: 0.0


    Quantiles:
         0.1%: 0.2521520655669675
           1%: 0.3725471824191853
           5%: 0.3725354736022214
          25%: 0.4117561085762543
          50%: 0.4649124729432545
          75%: 0.5163331075218496
          95%: 0.6168607054114867
          99%: 0.7069017681837765
        99.9%: 0.842320915032678

    std: 0.08234619289160715
    mean: 0.47279482318411425

ColumnProfile
    name: height
    type: FieldType.DECIMAL

    min: 43.0
    max: 83.0
    count: 18589.0
    missing_count: 0.0
    not_missing_count: 18589.0
    percent_missing: 0.0
    error_count: 809.0
    empty_count: 0.0


    Quantiles:
         0.1%: 62.945827067669164
           1%: 68.99758782005755
           5%: 68.99719101123586
          25%: 70.38494889805855
          50%: 72.0
          75%: 73.99753399388054
          95%: 76.0
          99%: 78.3517553191489
        99.9%: 80.62964464925763

    std: 2.598992233721804
    mean: 72.2352643419572

We can also specify a custom range for the scaling. Instead of [0, 1], let's choose [-10, 10].

In [6]:
df3 = df.min_max_scale(column='weight', range_min=-10, range_max=10)
df3.head(10)

    playerID    weight  height
0  aardsda01  0.980392    75.0
1  aaronha01 -0.980392    72.0
2  aaronto01 -0.196078    75.0
3   aasedo01 -0.196078    75.0
4   abadan01 -0.666667    73.0
5   abadfe01  2.156863    73.0
6  abadijo01 -0.039216    72.0
7  abbated01 -1.764706    71.0
8  abbeybe01 -1.372549    71.0
9  abbeych01 -1.843137    68.0

In some cases, we may want to manually provide the min and max of the data in the source column. For example, we may want to avoid a full data scan because the dataset is large and we already know the min and max. We can provide the known min and max to the `min_max_scaler` function. The column will be scaled using the provided values. Let's say we want to scale the height column with 50 inches (`data_min`) becoming 0 (`range_min`). The program will scan the data to get `data_max`, which will become 1 (`range_max`).

In [7]:
df4 = df.min_max_scale(column='height', data_min=50)
df4.get_profile()

ColumnProfile
    name: playerID
    type: FieldType.STRING

    min: aardsda01
    max: zwilldu01
    count: 18589.0
    missing_count: 0.0
    not_missing_count: 18589.0
    percent_missing: 0.0
    error_count: 0.0
    empty_count: 0.0


ColumnProfile
    name: weight
    type: FieldType.DECIMAL

    min: 65.0
    max: 320.0
    count: 18589.0
    missing_count: 0.0
    not_missing_count: 18589.0
    percent_missing: 0.0
    error_count: 872.0
    empty_count: 0.0


    Quantiles:
         0.1%: 129.29877671957675
           1%: 159.99953151689223
           5%: 159.99654576856648
          25%: 169.99780768694487
          50%: 183.55268060052987
          75%: 196.6551175790482
          95%: 222.46017100866118
          99%: 245.24211967545628
        99.9%: 279.7918333333329

    std: 20.998279187359834
    mean: 185.56267991194906

ColumnProfile
    name: height
    type: FieldType.DECIMAL

    min: -0.21212121212121213
    max: 1.0
    count: 18589.0
    missing_count: 0.0
    not_missing_count: 18589.0
    percent_missing: 0.0
    error_count: 809.0
    empty_count: 0.0


    Quantiles:
         0.1%: 0.39229778992936887
           1%: 0.5756844793956861
           5%: 0.575672454885938
          25%: 0.6177257241835924
          50%: 0.6666666666666666
          75%: 0.7271979998145622
          95%: 0.7878787878787878
          99%: 0.8591441005802711
        99.9%: 0.9281020304050631

    std: 0.07875734041581207
    mean: 0.6737958891502199

### Using a Min-Max Scaler Builder

For more flexibility when constructing the arguments for the min-max scaling, we can use a min-max scaler builder.

In [8]:
builder = df.builders.min_max_scale(column='weight')
builder

MinMaxScalerBuilder
    column: 'weight'
    range_min: 0
    range_max: 1
    data_min: None
    data_max: None

Calling `builder.learn()` will trigger a full data scan to see what `data_min` and `data_max` are. We can choose whether to use these values, or set custom values.

In [9]:
builder.learn()
builder

MinMaxScalerBuilder
    column: 'weight'
    range_min: 0
    range_max: 1
    data_min: 65.0
    data_max: 320.0

If we want to provide custom values for any of the arguments, we can simply update the builder object.

In [10]:
builder.range_max = 10
builder.data_min = 50
builder

MinMaxScalerBuilder
    column: 'weight'
    range_min: 0
    range_max: 10
    data_min: 50
    data_max: 320.0

When we are satisfied with the arguments, we will call `builder.to_dataflow()` to get the result. Note that the min and max values of the source column is preserved by the builder at this point. If we need to get the true `data_min` and `data_max` values again, we will need to set those arguments on the builder to `None`, and then call `builder.learn()` again.

In [11]:
df5 = builder.to_dataflow()
df5.head(25)

,playerID,weight,height
0,aardsda01,5.74074,75
1,aaronha01,4.81481,72
2,aaronto01,5.18519,75
3,aasedo01,5.18519,75
4,abadan01,4.96296,73
5,abadfe01,6.2963,73
6,abadijo01,5.25926,72
7,abbated01,4.44444,71
8,abbeybe01,4.62963,71
9,abbeych01,4.40741,68
10,abbotda01,5.18519,71
11,abbotfr01,4.81481,70
12,abbotgl01,5.55556,78
13,abbotje01,5.18519,74
14,abbotji01,5.55556,75
15,abbotku01,4.81481,71
16,abbotky01,5.55556,76
17,abbotod01,4.81481,74
18,abbotpa01,5,75
19,aberal01,5.37037,74
20,abercda01,"azureml.dataprep.native.DataPrepError(""'Micros...","azureml.dataprep.native.DataPrepError(""'Micros..."
21,abercre01,6.11111,75
22,abernbi01,5.18519,70
23,abernbr01,5,73
24,abernte01,5.92593,74