# Assertions
Copyright (c) Microsoft Corporation. All rights reserved.<br>
Licensed under the MIT License.

Frequently, the data we work with while cleaning and preparing data is just a subset of the total data we will need to work with in production. It is also common to be working on a snapshot of a live dataset that is continuously updated and augmented.

In these cases, some of the assumptions we make as part of our cleaning might turn out to be false. Columns that originally only contained numbers within a certain range might actually contain a wider range of values in later executions. These errors often result in either broken pipelines or bad data.

AzureML DataPrep supports creating assertions on data, which are evaluated as the pipeline is executed. These assertions enable us to verify that our assumptions on the data continue to be accurate and, when not, to handle failures in a clean way.

To demonstrate, we will load a dataset and then add some assertions based on what we can see in the first few rows.

In [1]:
from azureml.dataprep import smart_read_file

df = smart_read_file('./data/crime0-10.csv')
df.get_profile()

ColumnProfile
    name: Longitude
    type: FieldType.DECIMAL

    min: -87.800174996
    max: -87.644545209
    count: 10.0
    missing_count: 1.0
    error_count: 0.0

    lower_quartile: -87.72499244275
    median: -87.685233078
    upper_quartile: -87.65891481025
    std: 0.05125709218559632
    mean: -87.6973696417778

ColumnProfile
    name: ID
    type: FieldType.DECIMAL

    min: 10139697.0
    max: 10140868.0
    count: 10.0
    missing_count: 0.0
    error_count: 0.0

    lower_quartile: 10139762.0
    median: 10139830.5
    upper_quartile: 10140379.0
    std: 409.8056585475928
    mean: 10140062.299999999

ColumnProfile
    name: Location Description
    type: FieldType.STRING

    min: ALLEY
    max: VEHICLE NON-COMMERCIAL
    count: 10.0
    missing_count: 0.0
    error_count: 0.0

ColumnProfile
    name: Ward
    type: FieldType.DECIMAL

    min: 9.0
    max: 49.0
    count: 10.0
    missing_count: 0.0
    error_count: 0.0

    lower_quartile: 16.0
    median: 30.5
    upper_quartile: 41.0
    std: 14.167647024902273
    mean: 29.5

ColumnProfile
    name: Location
    type: FieldType.STRING

    min:
    max: (42.008124017, -87.65955018)
    count: 10.0
    missing_count: 0.0
    error_count: 0.0

ColumnProfile
    name: District
    type: FieldType.DECIMAL

    min: 5.0
    max: 24.0
    count: 10.0
    missing_count: 1.0
    error_count: 0.0

    lower_quartile: 8.75
    median: 12.0
    upper_quartile: 17.0
    std: 6.098724821177329
    mean: 13.222222222222221

ColumnProfile
    name: Primary Type
    type: FieldType.STRING

    min: ARSON
    max: THEFT
    count: 10.0
    missing_count: 0.0
    error_count: 0.0

ColumnProfile
    name: Y Coordinate
    type: FieldType.DECIMAL

    min: 1826485.0
    max: 1946271.0
    count: 10.0
    missing_count: 1.0
    error_count: 0.0

    lower_quartile: 1876206.25
    median: 1901632.0
    upper_quartile: 1932624.25
    std: 37733.23942825478
    mean: 1898273.3333333333

ColumnProfile
    name: Latitude
    type: FieldType.DECIMAL

    min: 41.6793109
    max: 42.008124017
    count: 10.0
    missing_count: 1.0
    error_count: 0.0

    lower_quartile: 41.81602052575
    median: 41.885610142
    upper_quartile: 41.9709022135
    std: 0.10364520556300641
    mean: 41.87661278344444

ColumnProfile
    name: Date
    type: FieldType.DATE

    min: 2015-07-05 22:10:00+00:00
    max: 2015-07-05 23:50:00+00:00
    count: 10.0
    missing_count: 0.0
    error_count: 0.0

ColumnProfile
    name: Description
    type: FieldType.STRING

    min: $500 AND UNDER
    max: TO VEHICLE
    count: 10.0
    missing_count: 0.0
    error_count: 0.0

ColumnProfile
    name: Domestic
    type: FieldType.BOOLEAN

    min: False
    max: True
    count: 10.0
    missing_count: 0.0
    error_count: 0.0

ColumnProfile
    name: X Coordinate
    type: FieldType.DECIMAL

    min: 1129230.0
    max: 1172409.0
    count: 10.0
    missing_count: 1.0
    error_count: 0.0

    lower_quartile: 1149945.5
    median: 1160997.0
    upper_quartile: 1167630.75
    std: 14052.038898125928
    mean: 1157453.7777777778

ColumnProfile
    name: Updated On
    type: FieldType.DATE

    min: 2015-07-12 12:42:46+00:00
    max: 2015-07-12 12:42:46+00:00
    count: 10.0
    missing_count: 0.0
    error_count: 0.0

ColumnProfile
    name: Beat
    type: FieldType.DECIMAL

    min: 524.0
    max: 2431.0
    count: 10.0
    missing_count: 0.0
    error_count: 0.0

    lower_quartile: 824.0
    median: 1118.0
    upper_quartile: 1613.0
    std: 633.1475516988296
    mean: 1263.3999999999999

ColumnProfile
    name: IUCR
    type: FieldType.DECIMAL

    min: 460.0
    max: 1811.0
    count: 10.0
    missing_count: 0.0
    error_count: 0.0

    lower_quartile: 610.0
    median: 975.0
    upper_quartile: 1320.0
    std: 435.0555647781608
    mean: 1008.7

ColumnProfile
    name: Year
    type: FieldType.DECIMAL

    min: 2015.0
    max: 2015.0
    count: 10.0
    missing_count: 0.0
    error_count: 0.0

    lower_quartile: 2015.0
    median: 2015.0
    upper_quartile: 2015.0
    std: 0.0
    mean: 2015.0

ColumnProfile
    name: Arrest
    type: FieldType.BOOLEAN

    min: False
    max: True
    count: 10.0
    missing_count: 0.0
    error_count: 0.0

ColumnProfile
    name: Community Area
    type: FieldType.DECIMAL

    min: 1.0
    max: 63.0
    count: 10.0
    missing_count: 0.0
    error_count: 0.0

    lower_quartile: 10.0
    median: 28.5
    upper_quartile: 53.0
    std: 23.281132083966863
    mean: 32.3

ColumnProfile
    name: Block
    type: FieldType.STRING

    min: 011XX W MORSE AVE
    max: 121XX S FRONT AVE
    count: 10.0
    missing_count: 0.0
    error_count: 0.0

ColumnProfile
    name: FBI Code
    type: FieldType.STRING

    min: 05
    max: 18
    count: 10.0
    missing_count: 0.0
    error_count: 0.0

ColumnProfile
    name: Case Number
    type: FieldType.STRING

    min: HY329177
    max: HY330421
    count: 10.0
    missing_count: 0.0
    error_count: 0.0

We can see there are latitude and longitude columns present in this dataset. By definition, these are constrained to specific ranges of values. We can assert that this is indeed the case so that if any records come through with invalid values, we detect them.

In [2]:
from azureml.dataprep import f_and, value

df = df.assert_value('Latitude', f_and(value <= 90, value >= -90), error_code='InvalidLatitude')
df = df.assert_value('Longitude', f_and(value <= 180, value >= -180), error_code='InvalidLongitude')
df.keep_columns(['Latitude', 'Longitude']).get_profile()

ColumnProfile
    name: Longitude
    type: FieldType.DECIMAL

    min: -87.800174996
    max: -87.644545209
    count: 10.0
    missing_count: 0.0
    error_count: 1.0

    lower_quartile: -87.72499244275
    median: -87.685233078
    upper_quartile: -87.65891481025
    std: 0.05125709218559632
    mean: -87.6973696417778

ColumnProfile
    name: Latitude
    type: FieldType.DECIMAL

    min: 41.6793109
    max: 42.008124017
    count: 10.0
    missing_count: 0.0
    error_count: 1.0

    lower_quartile: 41.81602052575
    median: 41.885610142
    upper_quartile: 41.9709022135
    std: 0.10364520556300641
    mean: 41.87661278344444

Any assertion failures are represented as Errors in the resulting dataset. From the profile above, you can see that the Error Count for both of these columns is 1. We can use a filter to retrieve the error and see what value caused the assertion to fail.

In [3]:
from azureml.dataprep import col

error_df = df.filter(col('Latitude').is_error())
error = error_df.head(10)['Latitude'][0]
print(error.originalValue)

None

Our assertion failed because we were not removing missing values from our data. At this point, we have two options: we can go back and edit our code to avoid this error in the first place or we can resolve it now. In this case, we will just filter these out.

In [4]:
from azureml.dataprep import f_not, LocalFileOutput
clean_df = df.filter(f_not(col('Latitude').is_error()))
clean_df.get_profile()

ColumnProfile
    name: Longitude
    type: FieldType.DECIMAL

    min: -87.800174996
    max: -87.644545209
    count: 9.0
    missing_count: 0.0
    error_count: 0.0

    lower_quartile: -87.72499244275
    median: -87.685233078
    upper_quartile: -87.65891481025
    std: 0.05125709218559632
    mean: -87.6973696417778

ColumnProfile
    name: ID
    type: FieldType.DECIMAL

    min: 10139697.0
    max: 10140868.0
    count: 9.0
    missing_count: 0.0
    error_count: 0.0

    lower_quartile: 10139752.0
    median: 10139776.0
    upper_quartile: 10140406.75
    std: 427.71683909319376
    mean: 10140039.22222222

ColumnProfile
    name: Location Description
    type: FieldType.STRING

    min: ALLEY
    max: VEHICLE NON-COMMERCIAL
    count: 9.0
    missing_count: 0.0
    error_count: 0.0

ColumnProfile
    name: Ward
    type: FieldType.DECIMAL

    min: 12.0
    max: 49.0
    count: 9.0
    missing_count: 0.0
    error_count: 0.0

    lower_quartile: 22.0
    median: 34.0
    upper_quartile: 42.25
    std: 12.940032629187781
    mean: 31.77777777777778

ColumnProfile
    name: Location
    type: FieldType.STRING

    min: (41.6793109, -87.644545209)
    max: (42.008124017, -87.65955018)
    count: 9.0
    missing_count: 0.0
    error_count: 0.0

ColumnProfile
    name: District
    type: FieldType.DECIMAL

    min: 5.0
    max: 24.0
    count: 9.0
    missing_count: 0.0
    error_count: 0.0

    lower_quartile: 8.75
    median: 12.0
    upper_quartile: 17.0
    std: 6.098724821177329
    mean: 13.222222222222221

ColumnProfile
    name: Primary Type
    type: FieldType.STRING

    min: ARSON
    max: THEFT
    count: 9.0
    missing_count: 0.0
    error_count: 0.0

ColumnProfile
    name: Y Coordinate
    type: FieldType.DECIMAL

    min: 1826485.0
    max: 1946271.0
    count: 9.0
    missing_count: 0.0
    error_count: 0.0

    lower_quartile: 1876206.25
    median: 1901632.0
    upper_quartile: 1932624.25
    std: 37733.23942825478
    mean: 1898273.3333333333

ColumnProfile
    name: Latitude
    type: FieldType.DECIMAL

    min: 41.6793109
    max: 42.008124017
    count: 9.0
    missing_count: 0.0
    error_count: 0.0

    lower_quartile: 41.81602052575
    median: 41.885610142
    upper_quartile: 41.9709022135
    std: 0.10364520556300641
    mean: 41.87661278344444

ColumnProfile
    name: Date
    type: FieldType.DATE

    min: 2015-07-05 22:10:00+00:00
    max: 2015-07-05 23:50:00+00:00
    count: 9.0
    missing_count: 0.0
    error_count: 0.0

ColumnProfile
    name: Description
    type: FieldType.STRING

    min: $500 AND UNDER
    max: TO VEHICLE
    count: 9.0
    missing_count: 0.0
    error_count: 0.0

ColumnProfile
    name: Domestic
    type: FieldType.BOOLEAN

    min: False
    max: True
    count: 9.0
    missing_count: 0.0
    error_count: 0.0

ColumnProfile
    name: X Coordinate
    type: FieldType.DECIMAL

    min: 1129230.0
    max: 1172409.0
    count: 9.0
    missing_count: 0.0
    error_count: 0.0

    lower_quartile: 1149945.5
    median: 1160997.0
    upper_quartile: 1167630.75
    std: 14052.038898125928
    mean: 1157453.7777777778

ColumnProfile
    name: Updated On
    type: FieldType.DATE

    min: 2015-07-12 12:42:46+00:00
    max: 2015-07-12 12:42:46+00:00
    count: 9.0
    missing_count: 0.0
    error_count: 0.0

ColumnProfile
    name: Beat
    type: FieldType.DECIMAL

    min: 524.0
    max: 2431.0
    count: 9.0
    missing_count: 0.0
    error_count: 0.0

    lower_quartile: 889.25
    median: 1215.0
    upper_quartile: 1717.75
    std: 613.7485234198124
    mean: 1344.6666666666667

ColumnProfile
    name: IUCR
    type: FieldType.DECIMAL

    min: 460.0
    max: 1811.0
    count: 9.0
    missing_count: 0.0
    error_count: 0.0

    lower_quartile: 767.5
    median: 1020.0
    upper_quartile: 1320.0
    std: 418.3132133275788
    mean: 1066.7777777777778

ColumnProfile
    name: Year
    type: FieldType.DECIMAL

    min: 2015.0
    max: 2015.0
    count: 9.0
    missing_count: 0.0
    error_count: 0.0

    lower_quartile: 2015.0
    median: 2015.0
    upper_quartile: 2015.0
    std: 0.0
    mean: 2015.0

ColumnProfile
    name: Arrest
    type: FieldType.BOOLEAN

    min: False
    max: True
    count: 9.0
    missing_count: 0.0
    error_count: 0.0

ColumnProfile
    name: Community Area
    type: FieldType.DECIMAL

    min: 1.0
    max: 63.0
    count: 9.0
    missing_count: 0.0
    error_count: 0.0

    lower_quartile: 8.25
    median: 28.0
    upper_quartile: 54.25
    std: 23.4574082114798
    mean: 30.0

ColumnProfile
    name: Block
    type: FieldType.STRING

    min: 011XX W MORSE AVE
    max: 118XX S PEORIA ST
    count: 9.0
    missing_count: 0.0
    error_count: 0.0

ColumnProfile
    name: FBI Code
    type: FieldType.STRING

    min: 05
    max: 18
    count: 9.0
    missing_count: 0.0
    error_count: 0.0

ColumnProfile
    name: Case Number
    type: FieldType.STRING

    min: HY329177
    max: HY330421
    count: 9.0
    missing_count: 0.0
    error_count: 0.0